### ISSUE TITLE
Fails to load in IE11

### ISSUE THREAD

**Issue by tomchiverton** [pipwerks/PDFObject#287]
Logs a syntax error pointing at line 237, which is an arrow function, so doesn't work

```
        if(customAttribute && customAttribute.key && reservedTokens.every(token => !customAttribute.key.includes(token))){
```

**Comment by tomchiverton** [comment]
Introduced by https://github.com/pipwerks/PDFObject/commit/af739c1e434efe165af10cb5540a66afb952aef7

**Comment by theodore-s-beers** [comment]
Good catch. Can presumably replace…

`reservedTokens.every(token => !customAttribute.key.includes(token))`

with...

```js
reservedTokens.every(function (token) {
  return !customAttribute.key.includes(token);
})
```

**Comment by pipwerks** [comment]
(Not saying I can't implement a fix, but I've spent over 25 years kowtowing to IE. I'd like to bury it for good.)

**Comment by tomchiverton** [comment]
We have a product with around 30% users still using IE11 on some of the long term support versions of Windows where it is still supported

**Comment by pipwerks** [comment]
Fixed. The fat arrow wasn't the only issue, IE11 also choked on the `includes()` function. Thanks for reporting

**Comment by pipwerks** [comment]
@tomchiverton Just curious, what's the use rate now? Do you know when the LTS for Windows/IE will expire? Everything I've read says IE11 is completely unsupported.

**Comment by tomchiverton** [comment]
Windows LTSC version is supported till 2027:
https://learn.microsoft.com/en-us/lifecycle/products/windows-10-enterprise-ltsc-2021

 We still see about 5%-10% IE11 usage, though this is dropping.
